
services:
  dev-db:
    image: postgres:17.5
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - test-network
networks:
  test-network: